[package]
name = "warp-starwars"
version = "0.1.1"
authors = ["sunli <scott_s829@163.com>"]
edition = "2018"

[dependencies]
async-graphql = { path = "../../.." }
async-graphql-warp = { path = "../../../integrations/warp" }
tokio = { version = "0.3.0", features = ["macros", "rt-multi-thread"] }
tokio-compat-02 = "0.1.2"
warp = "0.2"
starwars = { path = "../../models/starwars" }
http = "0.2"
