[package]
name = "actix-web-upload"
version = "0.1.0"
authors = ["sunli <scott_s829@163.com>"]
edition = "2018"

[dependencies]
async-graphql = "1.9.0"
async-graphql-actix-web = "1.0.5"
actix-web = "2.0.0"
actix-rt = "1.0.0"
files = { path = "../../models/files" }