[package]
name = "books"
version = "0.1.1"
authors = ["sunli <scott_s829@163.com>"]
edition = "2018"

[dependencies]
async-graphql = { path = "../../.." }
slab = "0.4.2"
tokio = { version = "0.2.0", features = ["time", "stream"] }
futures = "0.3.0"
once_cell = "1.0"
