[package]
name = "federation-accounts"
version = "0.1.0"
authors = ["sunli <scott_s829@163.com>"]
edition = "2018"

[dependencies]
async-graphql = "2.0.0-alpha.5"
async-graphql-warp = "2.0.0-alpha.5"
tokio = { version = "0.2", features = ["macros"] }
warp = "0.2"