[package]
name = "warp-defer"
version = "0.1.0"
authors = ["sunli <scott_s829@163.com>"]
edition = "2018"

[dependencies]
async-graphql = "1.16"
async-graphql-warp = "1.14.9"
tokio = { version = "0.2", features = ["macros", "time"] }
warp = "0.2"
http = "0.2"
