[package]
name = "warp-defer"
version = "0.1.0"
authors = ["sunli <scott_s829@163.com>"]
edition = "2018"

[dependencies]
async-graphql = { path = "C:\\Users\\scott\\Documents\\work\\async-graphql" }
async-graphql-warp = { path = "C:\\Users\\scott\\Documents\\work\\async-graphql\\async-graphql-warp" }
tokio = { version = "0.2", features = ["macros", "time"] }
warp = "0.2"
http = "0.2"
