[package]
name = "tide-dataloader"
version = "0.1.1"
authors = ["vkill <vkill.net@gmail.com>"]
edition = "2018"

[dependencies]
async-graphql = { path = "../../.." }
async-graphql-tide = { path = "../../../integrations/tide" }
tide = "0.14"
async-std = "1.5.0"
dataloader = "0.12.0"
sqlx = { version = "0.3.5", features = ["sqlite"] }
async-trait = "0.1.30"

[dev-dependencies]
serde_json = "1.0.51"
surf = "2.0.0-alpha.1"
