[package]
name = "warp-subscription"
version = "0.1.1"
authors = ["sunli <scott_s829@163.com>"]
edition = "2018"

[dependencies]
async-graphql = { path = "../../.." }
async-graphql-warp = { path = "../../../integrations/warp" }
tokio = { version = "0.2.0", features = ["macros", "rt-threaded"] }
warp = "0.2"
books = { path = "../../models/books" }
