[package]
name = "tide-starwars"
version = "0.1.0"
authors = ["vkill <vkill.net@gmail.com>"]
edition = "2018"

[dependencies]
async-graphql = "2.0.0-alpha.7"
async-graphql-tide = "2.0.0-alpha.7"
tide = "0.13"
async-std = "1.5.0"
starwars = { path = "../../models/starwars" }

[dev-dependencies]
serde_json = "1.0.51"
surf = "2.0.0-alpha.5"
