[package]
name = "tide-token-from-header"
version = "0.1.0"
authors = ["vkill <vkill.net@gmail.com>"]
edition = "2018"

[dependencies]
async-graphql = "1.16"
async-graphql-tide = "1.15.13"
tide = "0.13"
async-std = "1.5.0"

[dev-dependencies]
serde_json = "1.0.51"
surf = "2.0.0-alpha.1"
