[package]
name = "actix-web-starwars"
version = "0.1.0"
authors = ["sunli <scott_s829@163.com>"]
edition = "2018"

[dependencies]
async-graphql = "1.16"
async-graphql-actix-web = "1.4.17"
actix-web = "2.0.0"
actix-rt = "1.0.0"
starwars = { path = "../../models/starwars" }